@startuml Diagrama



interface Temperatura{
    + getTemperatura()
}

class Reactor implements Temperatura{
    + getTemperatura()
}


abstract class MecanismoDeSeguridad implements Temperatura{
    - temperaturaAEnfriar: Temperatura

    + setTemperaturaAEnfriar(c: Temperatura)
    + getTemperatura()
}

class BarrasDeControl extends MecanismoDeSeguridad{
    - barrasDeControl: BarraDeControl[]
    - temperaturaAEnfriar: Temperatura

    - porcentajeDeEnfriamiento()

    + setTemperaturaAEnfriar(c: Temperatura)
    + getTemperatura(){}
}

class Cliente{}

BarrasDeControl <-- Cliente

@enduml