@startuml Diagrama Clase

skinparam linetype ortho
skinparam arrow {
    Thickness 1
}
skinparam TitleFontSize 20

title Diagrama Clase

interface SubscriberReactor{
    + update(temperatura)
}

class Reactor {
- tempActual: number
- subscribers: List<SubscriberReactor>

+ subscribe(s: Subscriber)
+ unsubscribe(s: Subscriber)
+ notifySubscribers()

}

class BarraControl {
- tiempoVida: number

+ getTiempoDeVida(): number
+ getRedEnerTerm(): number
}

class ControladorBarrasDeControl{
    - barrasDeControl: List<BarraDeControl>

    + getBarrasDeControl(): List<BarraDeControl>
    + utilizarBarraDeControl(index: number): Resultado
    + retirarBarraDeControl(index: number): Resultado
    + remplazarBarraDeControl(index: number, BarraDeControl): Resultado

    + utilizarBarrasDeControl(): Resultado
    + retirarBarrasDeControl(): Resultado
}

class CensorTemperaturaReactor extends SubscriberReactor{
    - temperatura: number
    
    + getTemperatura(): number

    + update(temperatura)
}

class Sistema{
    - reactor: Reactor
    - censorTemperaturaReactor: CensorTemperaturaReactor
    - controladorBarrasDeControl: ControladorBarrasDeControl

    - tempNorMin: number = 280
    - tempNorMax: number = 330
    
    + sitCritica(): boolean

    + getTemperatura(): number
    + getTemperaturaReactor(): number
    + getEnergiaGenerada(): number
}

Reactor <-- Sistema
CensorTemperaturaReactor <-- Sistema
ControladorBarrasDeControl <-- Sistema

BarraControl <-- ControladorBarrasDeControl
@enduml